trigger:
 batch: true
 branches:
   include:
     - master
     - module

jobs:
- job: Windows_Current
  timeoutInMinutes: 5
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: ./.templates/pwsh.yml
    parameters:
      testTitle: 'Windows (Current)'

- job: Windows_Legacy
  timeoutInMinutes: 5
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: ./.templates/powershell.yml
    parameters:
      testTitle: 'Windows (Legacy)'

- job: Linux
  timeoutInMinutes: 5
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ./.templates/pwsh.yml
    parameters:
      testTitle: 'Linux'

- job: MacOS
  timeoutInMinutes: 5
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: ./.templates/pwsh.yml
    parameters:
      testTitle: 'MacOS'
